[package]
name = "elixir_state_in_rust_map"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "elixir_state_in_rust_map"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.23.0"
shared = {path = "../shared"}
